spring:
  application:
    name: settlement
  jackson:
    time-zone: Asia/Seoul
  datasource:
    url: jdbc:h2:mem:settlement;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
        timezone:
          default_storage: NORMALIZE
  h2:
    console:
      enabled: true
